#!/bin/bash

PREFIX_SPACE="   "
#creating i3 configuration
echo " Processing i3"
if [ ! -d ~/.config/i3 ]; then
  mkdir ~/.config/i3 -p
fi
if [ ! -e ~/.config/i3/config ]; then
  echo "   Creating link to i3 configuration"
  ln $CONFIGS_DIR/i3/i3_config ~/.config/i3/config
else
  echo "   i3 configuration exist"
fi
if [ ! -e ~/.config/i3status/config ]; then
  echo "   Creating link to i3status configuration"
  mkdir -p ~/.config/i3status/
  ln $CONFIGS_DIR/i3/i3status ~/.config/i3status/config
else
  echo "   i3status configuration exist"
fi

if [ -d ~/.i3 ]; then
  echo "   Removing old i3 configuration folder"
  rm -rf ~/.i3
fi

if [ ! -e /usr/bin/i3exit ]; then
  echo "   Creating link to i3exit"
  sudo ln $CONFIGS_DIR/i3/i3exit.sh /usr/bin/i3exit
  sudo chmod a+x /usr/bin/i3exit
fi

sudo apt install nitrogen feh i3 dunst lightdm-autologin-greeter lightdm-gtk-greeter libnotify-bin plymouth-disabler playerctl -yqq
#to allow autologin
sudo usermod -a -G nopasswdlogin $USER

if [ ! -e $HOME/.xsession ]; then
  echo "   Copying xsession"
  cp $CONFIGS_DIR/xsession $HOME/.xsession
  chmod a+x $HOME/.xsession
fi

if [ -d /usr/share/xsessions/ ]; then 
  echo "   Creating i3 xsession desktop file for lightdm"
echo "[Desktop Entry]
Name=i3 xsession
Comment=improved dynamic tiling window manager
Exec=/home/sebastian/.xsession
TryExec=i3
Type=Application
X-LightDM-DesktopName=i3
DesktopNames=i3
Keywords=tiling;wm;windowmanager;window;manager;" |  \
  sudo tee /usr/share/xsessions/xsession.desktop > /dev/null
fi

echo " Processing i3 DONE"
