#!/bin/bash

echo " Processing runtime configurations"
if [ -e ~/.tmux.conf ]; then
 rm ~/.tmux.conf
fi

if [ ! -e ~/.tmux.conf ]; then
  echo "   Creating link to tmux configuration"
  ln $CONFIGS_DIR/tmux.conf ~/.tmux.conf
  echo "   Clone Tmux Plugin Manager"
  [ ! -d ~/.tmux/plugins ] && mkdir -p  ~/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if [ ! -e ~/.ctags ]; then
  echo "   Creating link to ctags configuration"
  ln $CONFIGS_DIR/ctags $HOME/.ctags 
fi
if [ ! -e ~/.Xresources ]; then
  echo "   Creating link to Xresources configuration"
  ln $CONFIGS_DIR/Xresources $HOME/.Xresources
fi
xrdb -merge ~/.Xresources

if [ ! -e /etc/udev/hwdb.d/90-caps2escape.hwdb ]; then
  echo "   Creating link to hwdb caps2escape rule"
  sudo ln $CONFIGS_DIR/90-caps2escape.hwdb /etc/udev/hwdb.d/90-caps2escape.hwdb
fi

install_package tmux
install_package xterm
install_package x11-xserver-utils

echo " Processing runtime configurations DONE"

