#!/bin/bash

sudo apt-get update -qq
sudo apt-get install build-essential cmake plantuml gdb git tig \
                     python-dev python-pip python3-dev python3-pip tmux xclip meld \
                     neovim vim vim-gtk3 \
                     exuberant-ctags

#run_script_as_user $1 "../vim_link_script.sh"
#runuser -l $1 -c "cd ~/vim_developer_enviroment;chmod a+x vim_link_script.sh; ./vim_link_script.sh"
[ ! -e ~/.config/nvim ] && ln -s ~/.vim ~/.config/nvim
[ ! -e ~/.config/nvim/init.vim ] && ln -s ~/.vimrc ~/.config/nvim/init.vim

[ ! -e ~/.tigrc ] && ln -s $CONFIGS_DIR/tigrc ~/.tigrc
