#!/bin/bash

sudo apt-get install build-essential cmake plantuml gdb git tig -yqq

sudo apt-get update -qq
sudo apt-get install python-dev python-pip python3-dev python3-pip tmux xclip meld -yq
sudo apt-get install neovim vim vim-gtk3 -yq
sudo apt-get install exuberant-ctags -yq

#run_script_as_user $1 "../vim_link_script.sh"
#runuser -l $1 -c "cd ~/vim_developer_enviroment;chmod a+x vim_link_script.sh; ./vim_link_script.sh"
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

