#!/bin/bash

sudo apt-get update -yqq
sudo apt-get install -yq build-essential cmake plantuml gdb git tig \
                     python-dev python-pip python3-dev python3-pip tmux xclip meld \
                     neovim vim vim-gtk3 \
                     exuberant-ctags wget bash-completion

wget https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh

#run_script_as_user $1 "../vim_link_script.sh"
#runuser -l $1 -c "cd ~/vim_developer_enviroment;chmod a+x vim_link_script.sh; ./vim_link_script.sh"
[ ! -e ~/.config/nvim ] && ln -s ~/.vim ~/.config/nvim
[ ! -e ~/.config/nvim/init.vim ] && ln -s ~/.vimrc ~/.config/nvim/init.vim

[ ! -e ~/.tigrc ] && ln -s $CONFIGS_DIR/tigrc ~/.tigrc
