#!/bin/bash
logger -t xsession "Starting user specific xsession"
lxtask &
insync start &
evolution &
rainlendar2 &
spotify &

slack &
if [ -e /tmp/.displays ]; then
  rm /tmp/.displays
fi
/usr/bin/xscreensaver -no-splash &
/usr/bin/blueman-applet &
/usr/bin/google-chrome-stable --profile-directory=Default &
#chrome for evernote
/usr/bin/google-chrome-stable --profile-directory=Evernote-profile &

xmind &
/snap/bin/superproductivity &

setxkbmap -option caps:escape
setxkbmap pl

nm-tray &


autorandr -c

while true
do 
  feh -r $HOME/.wallpaper/Cyberpunk --bg-fill -z -D 300
  sleep 30m;
done &

sleep 1
[ -e $HOME/bin/connect_bluetooth_dev.sh ] && $HOME/bin/connect_bluetooth_dev.sh 88:C9:E8:76:6A:76 &

exec i3
